### ISSUE TITLE
How can i use your Program?

### ISSUE THREAD

**Issue by mrCCS** [gottagofaster236/Twitch-Channel-Points-Miner#1]
Hey i would like to test your Program, how do i use it? Is it possible to run it on armf? Like an Raspi?

**Comment by gottagofaster236** [comment]
Hey! I haven't tested this program on any system other than Windows, but it should be portable (as it's written on Python). You can try and test it out. ([Here](https://www.reddit.com/r/selenium/comments/7341wt/success_how_to_run_selenium_chrome_webdriver_on/)'s a link how to set up selenium on a Raspberry Pi).

**Comment by mrCCS** [comment]
can you maybe help me with that? That would be soo awsome

**Comment by mrCCS** [comment]
python main.py
  File "main.py", line 13
    driver: HiddenChromeWebDriver
          ^
SyntaxError: invalid syntax

Can you help me with that? This pops up when i try to start ne main.py

**Comment by gottagofaster236** [comment]
That means you have an old version of Python, which doesn't support type hints (which were added in **Python 3.5**).

**Comment by mrCCS** [comment]
I Updated to python 3.8.3 now i get this

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from selenium.common.exceptions import *
ModuleNotFoundError: No module named 'selenium'

**Comment by gottagofaster236** [comment]
That's because you have to install selenium. To do this, you gotta write `pip install selenium` in the command line.

**Comment by mrCCS** [comment]
Do I need to install it in the folder of python or the main.py script or just normal without anything in the command line? Cause I installed it already

**Comment by mrCCS** [comment]
from selenium import webdriver

driver = webdriver.Chrome()

driver.get("https://www.twitch.tv") 

when i run this Basic script its openting Chromium, but when i try to start your script its not working ill get the error 

error in line 13 of your script at driver : <- HiddenChromeWebDriver the : are the problem atm the error is: "SyntaxError: invalid syntax"
