### ISSUE TITLE
Idle in much Channels

### ISSUE THREAD

**Issue by mrcsdl** [gottagofaster236/Twitch-Channel-Points-Miner#10]
When I start the bot, type in like 18 Channels it’s only idle 3or 4 of them. When I type in 9 than it works for all of them. Is this a bug or a problem with twitch?

**Comment by gottagofaster236** [comment]
I'm not sure, I'm gonna test it. If all of the requests are successful (200 status codes, etc.), then it's just Twitch limiting your channel points...

**Comment by gottagofaster236** [comment]
Does it still idle if you launch several instances of the Twitch Miner?
For example, if you put streamers A and B in the first process, and streamers C and D in the second.

**Comment by mrCCS** [comment]
ill test it out, give me some Time. I come back and give you the info

**Comment by mrCCS** [comment]
so its only works for two Channels at once. I tryed out more processes that didnt worked for me.

**Comment by gottagofaster236** [comment]
Thanks for the information.
It seems there is some kind of a hard limit (**no more than 2 channels at one time**). I observe the same behaviour on my side. 
I'll investigate further, but I think it's done by Twitch (to prevent you from getting way too many points).

**Comment by gottagofaster236** [comment]
I think the same behaviour occurs if you open three tabs of Twitch at the same time (have to check that)

**Comment by mrCCS** [comment]
Okay, so I think we can close this issue. Thanks for your work, it’s nice to use it on my raspberry pi. It’s working well and takes like 1% cpu that’s awesome

**Comment by gottagofaster236** [comment]
Gotta add a message to the user when more than two channels are online at one time

**Comment by zhenyamega** [comment]
need write a system of priorities for choosing streamers

**Comment by trimbe** [comment]
Just wanted to confirm that if you open more than 2 tabs of the website, the same issue occurs. Channels without points enabled will also count towards the limit so it's a limitation on `minute-watched` events rather than specifically channel points.
