### ISSUE TITLE
work only on 2 channel simultaneously

### ISSUE THREAD

**Issue by brottobhmg** [gottagofaster236/Twitch-Channel-Points-Miner#15]
i put up a channel list but this only focuses on 2 of them. is it a limit?

**Comment by brottobhmg** [comment]
tried it on windows 10

**Comment by gottagofaster236** [comment]
Yeah, it's a Twitch limit. You can't watch more than two streamers simultaneously. (Probably should write this in README). That's why there's a priority system - you have to input the most important for you streamers first.
