### ISSUE TITLE
Heroku compatibility

### ISSUE THREAD

**Issue by deion** [gottagofaster236/Twitch-Channel-Points-Miner#17]
Is it possible to deploy this to heroku?

**Comment by gottagofaster236** [comment]
It probably is possible, although I've never used heroku. I myself host the script on pythonanywhere (not an advertisement 😄)

**Comment by deion** [comment]
do you have a recommendation for plan settings?

**Comment by gottagofaster236** [comment]
I use all lowest, this miner is really light on the CPU

**Comment by wuppyz** [comment]
> It probably is possible, although I've never used heroku. I myself host the script on pythonanywhere (not an advertisement 😄)

I'm trying pythonanywhere but can't get it to work. I try python3 main.py and this is what happens:
`Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from login import check_login
  File "/home/puppyonkik/login.py", line 3, in <module>
    import browser_cookie3
ModuleNotFoundError: No module named 'browser_cookie3'`

**Comment by gottagofaster236** [comment]
@wuppyz You have to install browser_cookie3. Just open up a console and type in _pip3 install browser_cookie3_. Also, it won't work on the free plan (as outgoing requests are limited on free accounts).

**Comment by wuppyz** [comment]
> @wuppyz You have to install browser_cookie3. Just open up a console and type in _pip3 install browser_cookie3_. Also, it won't work on the free plan (as outgoing requests are limited on free accounts).

I've done that and still get that exact same problem. I've also bought the $5 plan on there. Unsure what's wrong. Could be a pathing issue? Not too sure.
