### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by Pentalex** [gottagofaster236/Twitch-Channel-Points-Miner#18]
Do you know if this would work on multiple accounts/multiple instances?

**Comment by gottagofaster236** [comment]
I've not implemented it, but it is possible.

This program saves cookies in the directory with source. So, one of the options is to **have two copies of this program somewhere on your hard disk**, with different users logged in.

**Comment by gottagofaster236** [comment]
@Pentalex does it work for you? Should we close the issue?

**Comment by Pentalex** [comment]
Thanks for the info. Yeah we can go ahead and close it now.
