### ISSUE TITLE
does not redeem the 50 points

### ISSUE THREAD

**Issue by brottobhmg** [gottagofaster236/Twitch-Channel-Points-Miner#20]
with the version downloaded yesterday, it does not redeem the 50 points but only the 10 every 5 minutes

![Screenshot (36)](https://user-images.githubusercontent.com/73940120/101486580-2aef4e00-395d-11eb-97e2-a27727b43638.png)

**Comment by gottagofaster236** [comment]
Yeah right, gotta fix this

**Comment by gottagofaster236** [comment]
Thanks for reporting!
