### ISSUE TITLE
Multiple streamers

### ISSUE THREAD

**Issue by EnforcerTTV** [gottagofaster236/Twitch-Channel-Points-Miner#22]
How many streamers do you think its optimized to support, Only seems to do 2 not even of the streamers out of a 10 streamer list, Is there a max for it to work effectively or what exactly? Whats my best options for this.

**Comment by gottagofaster236** [comment]
It's a Twitch limit, you can't watch more than 2 channels at one time. Have to add this to readme...

**Comment by EnforcerTTV** [comment]
> It's a Twitch limit, you can't watch more than 2 channels at one time. Have to add this to readme...

ty
