### ISSUE TITLE
channels not detected as going live

### ISSUE THREAD

**Issue by ctlaltdefeat** [gottagofaster236/Twitch-Channel-Points-Miner#24]
I'm not sure if it's a regression in the code or something on twitch's end, but it doesn't seem like channels are detected as going live anymore. 
Bonus points are being collected fine from the two channels that happen to be live when starting the program, but after they go offline it doesn't ever pick up on any other channels.

**Comment by mrcsdl** [comment]
got the same problem.

**Comment by fergilicious** [comment]
Same. It worked fine before the pubsub update. Now it doesn't work anymore. It only works if you manually start it when the stream is already online. After the stream goes offline it stops working.

**Comment by gottagofaster236** [comment]
Fixed that (I hope)

**Comment by gottagofaster236** [comment]
Reopen the issue if it's not fixed XD
