### ISSUE TITLE
Automating Login

### ISSUE THREAD

**Issue by BoraxTheClean** [gottagofaster236/Twitch-Channel-Points-Miner#25]
Hello Maintainers-

Do you know if it is against TOS (or other laws) to automate Twitch logins? I was wanting to host this solution on AWS Lambda and remove the need to have it running on a thread on a machine I have direct access to.

Before I go further down this rabbit hole, I'd like to know if you had tried to automate logins or have any advice on the matter.

Thanks for making this cool project!

Best,
Owen

**Comment by gottagofaster236** [comment]
Hey, this whole repository is against the TOS (as it uses undocumented APIs).
When you login, your login information is saved in a "twitch-cookies.pkl" file.
You can copy it to another location so that you don't have to login again.

**Comment by gottagofaster236** [comment]
Did I answer your question? Should we close the issue?

**Comment by BoraxTheClean** [comment]
Yep, thanks for the advice @gottagofaster236!

**Comment by gottagofaster236** [comment]
You're welcome!
