### ISSUE TITLE
is this repl.it compatibile?

### ISSUE THREAD

**Issue by jozz024** [gottagofaster236/Twitch-Channel-Points-Miner#27]
I'm trying to setup an auto farmer with repl.it, but once I hit the run button it doesn't do anything, and the run button reappears after a millisecond.

**Comment by heyimrendy** [comment]
Just rent cheap VPS, should be enough. Don't know if you could run script without premium repl, it works with github codespace.

**Comment by heyimrendy** [comment]
@jozz024 Don't know if you still looking for answer or already solve it. After testing with repl.it, you actually need to change the import module.
After you create new repl and import from Github, open `pubsub.py` change line 5 into `import websocket  #upm package(websocket-client)`

And then scroll down repl folder and delete `requirements.txt`. After that you should be able to click the run button, and make sure file `.replit` file:
```
language = "python3"
run = "python main.py"
```

**Comment by jozz024** [comment]
How do I install “browsercookies3”?

**Comment by jozz024** [comment]
Oops nvm I figured it out, thanks for your help!
