### ISSUE TITLE
No longer running

### ISSUE THREAD

**Issue by deion** [gottagofaster236/Twitch-Channel-Points-Miner#28]
Tool ran fine all night but when i restarted it today im faced with this

https://pastebin.com/XHfGfwa5

**Comment by gottagofaster236** [comment]
You have to update numpy like this:

`pip install numpy --upgrade`

**Comment by deion** [comment]
requirement already satisfied

**Comment by deion** [comment]
found the issue. It was indeed with numPy. 

If anyone sees this in the future check the version of your numPy
1.19.4 causes errors

To fix simply downgrade 
pip install numpy==1.19.3

**Comment by gottagofaster236** [comment]
Nice! Should we close the issue then?
