### ISSUE TITLE
better 'Watch Streak' handling in priority system

### ISSUE THREAD

**Issue by testdev123456** [gottagofaster236/Twitch-Channel-Points-Miner#30]
Since a Watch Streak gives 450 points by viewing only (five?) minutes of a stream, I would modify the priority system to 'forget' priorities for a minute and switch to the newest live stream until collects the 450 points, then resume normally watching the top priority live stream. 
I think it makes sense giving up just 10 points (5 minutes) of a top streamer in order to grab the 450 points of my 3rd or 4th ranked live stream.

**Comment by Tkd-Alex** [comment]
If someone is interested to this feature please check my fork on branch **watch-streak**

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/watch-streak
