### ISSUE TITLE
I can use it on windows but can't use on mac properly

### ISSUE THREAD

**Issue by aswq206** [gottagofaster236/Twitch-Channel-Points-Miner#32]
i can use it on windows but can't use it on mac
it'll stuck at 
"Reconnecting to Twitch Pubsub serbver in 30 seconds."
it can get 10 point in 5 min
but can't auto claim bonus

**Comment by gottagofaster236** [comment]
Hmm, that is weird. Maybe there's an exception inside the `on_message`  function which causes the connection to close (as websocket-client does not print exceptions). Will have to check that.

**Comment by aswq206** [comment]
things being OK after I reinstall python3 ... 
thanks a lot for help!
