### ISSUE TITLE
WebDriver-less approach to receiving channel points

### ISSUE THREAD

**Issue by ctlaltdefeat** [gottagofaster236/Twitch-Channel-Points-Miner#4]
It could be cool to try to isolate what exactly causes channel points to be received, so that one can mine them by communicating with the appropriate servers without using the heavy webdriver.
I tried playing around with it a bit but I haven't been able to narrow it down. Is it actually downloading the stream segments, something to do with the gql API, something to do with the pubsub WS, or all of the above?

**Comment by gottagofaster236** [comment]
Hey, I actually was doing that for the past few weeks (and succeeded in that), the only thing left is login. I'm gonna commit it here when I'll finish 😁

**Comment by ctlaltdefeat** [comment]
Nice! I guess we'll close this issue when it's committed.

**Comment by gottagofaster236** [comment]
Okay, I've commited it, the only unimplemented part for now is raid following.
