### ISSUE TITLE
Network issue after program is left running

### ISSUE THREAD

**Issue by deion** [gottagofaster236/Twitch-Channel-Points-Miner#5]
Program launches fine and collects for awhile but then it gets this issues 

https://pastebin.com/gHtZ9jzR

**Comment by gottagofaster236** [comment]
Hello, thanks for your bug report. It seems like a problem with Twitch servers or your internet connection, and it's probably easy to fix by just reconnecting 🤔 Did this happen several times, or just a single crash?

**Comment by deion** [comment]
I've tried 5 times to restart/use all online streamers but after awhile it also shows that error I linked above. I'm thinking maybe twitch servers as my internet connection is stable. If there is any more information you need from me I'm happy to provide it

**Comment by gottagofaster236** [comment]
Does this commit fix the bug on your side? 2e81610fc686a845e8fcca88ea3a1fcd8ab551a9

**Comment by deion** [comment]
It appears to have fixed it!

https://pastebin.com/2wccfrwQ

See pastebin above

**Comment by gottagofaster236** [comment]
Okay, thanks for the info.
